ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
          backend:
            serviceName: api-gateway
            servicePort: 80
        - path: /
          pathType: Prefix
          backend:
            serviceName: frontend
            servicePort: 80 