apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}
  namespace: ecommerce
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecommerce.selectorLabels" . | nindent 4 }}
